import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { chromium } from '@playwright/test';
import { createApp } from '../dist/server/app.js';
import { Store } from '../dist/server/store.js';
import { Auth } from '../dist/server/auth.js';

// Geçici veriler; canlı model çağrısı veya üretim girişini atlayan yol yoktur.
const dir = mkdtempSync(path.join(tmpdir(), 'intrem-browser-'));
const output = path.resolve('output/playwright');
mkdirSync(output, { recursive: true });
const origin = 'http://localhost:4111';
const config = { dataDir: dir, dbPath: path.join(dir, 'db.sqlite'), host: '127.0.0.1', port: 4111, origin, rpId: 'localhost', secureCookies: false, allowedRoots: [dir], claudeHome: path.join(dir, '.claude'), claudeExecutable: 'missing-claude', codexExecutable: 'missing-codex', omnirouteUrl: null, pushSubject: origin };
const store = new Store(config.dbPath), auth = new Auth(store.db);
const bootstrap = auth.resetBootstrap();
const app = await createApp({ config, store, auth });
let browser;
const errors = [];
const waitFor = async (condition, label) => {
  const until = Date.now() + 12000;
  while (Date.now() < until) { if (await condition()) return; await new Promise(resolve => setTimeout(resolve, 100)); }
  throw new Error(`Doğrulanamadı: ${label}`);
};
try {
  await app.listen({ host: config.host, port: config.port });
  browser = await chromium.launch({ headless: true });
  const context = await browser.newContext({ viewport: { width: 1440, height: 960 } });
  const page = await context.newPage();
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(`${origin}/info`);
  await page.getByRole('heading', { name: 'intRem kullanım rehberi', exact: true }).waitFor({ timeout: 5000 });
  assert.equal((await fetch(`${origin}/api/snapshot`)).status, 401, 'Public guide must not open protected data');
  await page.getByRole('link', { name: 'Sık sorulanlar', exact: true }).click();
  const faq = page.locator('summary').filter({ hasText: 'Başka bir cihazdan nasıl giriş yaparım?' });
  await faq.focus();
  await page.keyboard.press('Enter');
  assert.equal(await faq.evaluate(node => node.parentElement.open), true, 'FAQ opens with keyboard');
  for (const viewport of [{ width: 320, height: 740 }, { width: 375, height: 812 }, { width: 768, height: 1024 }, { width: 812, height: 375 }, { width: 1440, height: 960 }]) {
    await page.setViewportSize(viewport);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `guide overflow ${viewport.width}`);
    assert.equal(await page.locator('.info-toc a, .info-header a, summary').evaluateAll(nodes => nodes.every(node => node.getBoundingClientRect().height >= 44)), true, 'guide touch targets');
    await page.getByRole('link', { name: 'Uygulamayı aç', exact: true }).last().scrollIntoViewIfNeeded();
    const footer = await page.getByRole('link', { name: 'Uygulamayı aç', exact: true }).last().boundingBox();
    assert.ok(footer && footer.y >= 0 && footer.y + footer.height <= viewport.height, 'guide footer reachable');
  }
  await page.setViewportSize({ width: 640, height: 900 });
  await page.evaluate(() => { document.body.style.zoom = '2'; });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'guide 200% reflow');
  await page.evaluate(() => { document.body.style.zoom = ''; });
  await page.setViewportSize({ width: 375, height: 812 });
  await page.evaluate(() => localStorage.setItem('intrem:theme', 'dark'));
  await page.reload();
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark');
  await page.evaluate(() => scrollTo(0, 0));
  await page.screenshot({ path: path.join(output, 'info-mobile-dark.png'), fullPage: true });
  await page.emulateMedia({ reducedMotion: 'reduce', colorScheme: 'light' });
  await page.evaluate(() => localStorage.setItem('intrem:theme', 'system'));
  await page.reload();
  await page.screenshot({ path: path.join(output, 'info-mobile.png'), fullPage: true });
  await page.setViewportSize({ width: 1440, height: 960 });
  await page.screenshot({ path: path.join(output, 'info-desktop.png'), fullPage: true });
  await page.getByRole('link', { name: 'Uygulamayı aç', exact: true }).first().click();
  await page.getByRole('heading', { name: 'İlk cihazınızı bağlayın' }).waitFor();
  await page.getByRole('link', { name: 'Kullanım rehberi', exact: true }).click();
  await page.getByRole('heading', { name: 'Kurulum anahtarı nedir?', exact: true }).waitFor();
  await page.getByRole('link', { name: 'Uygulamayı aç', exact: true }).first().click();
  const cdp = await context.newCDPSession(page);
  await cdp.send('WebAuthn.enable');
  await cdp.send('WebAuthn.addVirtualAuthenticator', { options: { protocol: 'ctap2', transport: 'internal', hasResidentKey: true, hasUserVerification: true, isUserVerified: true, automaticPresenceSimulation: true } });
  await page.goto(origin);
  await page.getByRole('heading', { name: 'İlk cihazınızı bağlayın' }).waitFor();
  await page.screenshot({ path: path.join(output, 'login-desktop.png') });
  await page.getByLabel('Kurulum anahtarı').fill(bootstrap);
  await page.getByRole('button', { name: 'Passkey oluştur ve bağlan' }).click();
  await page.getByRole('navigation', { name: 'Ana gezinme' }).waitFor();
  assert.equal(auth.hasCredentials(), true);
  await page.getByRole('link', { name: 'Kullanım rehberi', exact: true }).click();
  await page.getByRole('heading', { name: 'intRem kullanım rehberi', exact: true }).waitFor();
  await page.getByRole('link', { name: 'Uygulamayı aç', exact: true }).first().click();
  await page.getByRole('navigation', { name: 'Ana gezinme' }).waitFor();
  await page.getByRole('button', { name: 'Proje ekle', exact: true }).first().click();
  await page.getByLabel('Proje adı', { exact: true }).fill('Pilot uygulama');
  await page.getByLabel('Sunucudaki çalışma dizini').fill(dir);
  await page.getByRole('button', { name: 'Projeyi ekle', exact: true }).click();
  await waitFor(() => store.listProjects().length === 1, 'proje');
  await page.getByRole('button', { name: 'Yeni oturum başlat', exact: true }).first().click();
  await page.getByLabel('Oturum adı', { exact: false }).fill('Mobil kontrol pilotu');
  await page.getByRole('button', { name: 'Oturumu oluştur' }).click();
  await waitFor(() => store.listSessions().length === 1, 'oturum');
  const session = store.listSessions()[0];
  const sentIds = [];
  let drop = true;
  await page.route('**/api/sessions/*/messages', async route => {
    if (route.request().method() !== 'POST') return route.continue();
    sentIds.push(route.request().postDataJSON().clientId);
    if (drop) { drop = false; return route.abort('failed'); }
    return route.continue();
  });
  await page.getByLabel('Bu oturuma mesaj', { exact: true }).fill('Belirsiz HTTP gönderim testi');
  await page.getByRole('button', { name: 'Mesajı bu oturuma gönder' }).click();
  await page.getByRole('button', { name: 'Aynı kimlikle yeniden dene' }).waitFor();
  await page.reload();
  await page.getByRole('button', { name: 'Aynı kimlikle yeniden dene' }).waitFor();
  assert.equal(await page.getByRole('button', { name: 'Mesajı bu oturuma gönder' }).isDisabled(), true);
  await page.getByRole('button', { name: 'Aynı kimlikle yeniden dene' }).click();
  await waitFor(() => store.listMessages(session.id).some(m => m.role === 'user'), 'aynı kimlikle gönderim');
  assert.equal(sentIds.length, 2); assert.equal(sentIds[0], sentIds[1]);
  assert.equal(store.listMessages(session.id).filter(m => m.role === 'user').length, 1);
  store.cancelMessage(store.listMessages(session.id).find(m => m.role === 'user').id);
  store.setSetting('runnerHeartbeat', new Date().toISOString());
  await page.getByRole('button', { name: 'Codex ile incele' }).click();
  await page.getByRole('button', { name: 'İncelemeyi başlat', exact: true }).click();
  await waitFor(() => store.listReviews(session.id).length === 1, 'Codex inceleme isteği');
  store.updateReview(store.listReviews(session.id)[0].id, 'completed', 'Tarayıcı test verisi: inceleme çıktısı.', 'test-revision', 0);
  store.appendMessage(session.id, 'assistant', 'Proje hazır. Sonraki adım için tercihinizi bekliyorum.');
  const interaction = store.createInteraction({ sessionId: session.id, generation: session.generation, requestId: 'browser-fixture-question', kind: 'question', toolName: 'AskUserQuestion', input: { questions: [{ question: 'Hangi ortamda devam edelim?', options: [{ label: 'Pilot', description: 'Yalıtılmış deneme ortamı' }, { label: 'Geliştirme', description: 'Yerel geliştirme ortamı' }] }] }, expiresAt: new Date(Date.now() + 600000).toISOString() });
  store.updateSession(session.id, { state: 'waiting_answer' });
  await page.getByText('Proje hazır.', { exact: false }).waitFor();
  await page.screenshot({ path: path.join(output, 'sessions-desktop.png') });
  for (const width of [320, 375, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: 900 });
    await page.waitForTimeout(200);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true, `yatay taşma ${width}`);
  }
  for (const viewport of [{ width: 812, height: 375 }, { width: 390, height: 400 }]) {
    await page.setViewportSize(viewport);
    const send = page.getByRole('button', { name: 'Mesajı bu oturuma gönder' });
    await send.scrollIntoViewIfNeeded();
    const hiddenScroll = await send.evaluate(node => {
      const clipped = [];
      for (let parent = node.parentElement; parent; parent = parent.parentElement) {
        if (parent.scrollTop > 1 && ['hidden', 'clip'].includes(getComputedStyle(parent).overflowY)) clipped.push(parent.className);
      }
      return clipped;
    });
    assert.deepEqual(hiddenScroll, [], 'composer must be reachable without scrolling a hidden ancestor');
    const box = await send.boundingBox();
    const nav = await page.getByRole('navigation', { name: 'Mobil ana gezinme' }).boundingBox();
    assert.ok(box && nav && box.y >= 0 && box.y + box.height <= nav.y, `short viewport composer reachable ${viewport.width}x${viewport.height}`);
    assert.equal(await send.evaluate(node => { const r = node.getBoundingClientRect(); return node.contains(document.elementFromPoint(r.x + r.width / 2, r.y + r.height / 2)); }), true, 'send target not clipped');
    await page.screenshot({ path: path.join(output, `conversation-short-${viewport.width}.png`) });
  }
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: path.join(output, 'conversation-mobile.png') });
  const sendBox = await page.getByRole('button', { name: 'Mesajı bu oturuma gönder' }).boundingBox();
  const navBox = await page.getByRole('navigation', { name: 'Mobil ana gezinme' }).boundingBox();
  assert.ok(sendBox && navBox && sendBox.y + sendBox.height <= navBox.y, 'gönder düğmesi mobil gezinmenin üstünde');
  const answerButton = page.getByRole('button', { name: 'İncele', exact: true });
  await answerButton.focus();
  await page.keyboard.press('Enter');
  await page.getByRole('dialog', { name: 'Claude cevabınızı bekliyor' }).waitFor();
  for (let i = 0; i < 8; i++) {
    await page.keyboard.press('Tab');
    assert.equal(await page.evaluate(() => !!document.activeElement?.closest('dialog')), true, 'odak karar penceresinde kalır');
  }
  await page.keyboard.press('Escape');
  await page.getByRole('dialog', { name: 'Claude cevabınızı bekliyor' }).waitFor({ state: 'hidden' });
  assert.equal(await answerButton.evaluate(node => node === document.activeElement), true, 'odak karar düğmesine geri döner');
  await page.keyboard.press('Enter');
  await page.getByRole('radio', { name: /Pilot/ }).focus();
  await page.keyboard.press('Space');
  await page.screenshot({ path: path.join(output, 'question-mobile.png') });
  await page.getByRole('button', { name: 'Yanıtı gönder', exact: true }).focus();
  await page.keyboard.press('Enter');
  await waitFor(() => store.getInteraction(interaction.id).status === 'answered', 'soru yanıtı');
  assert.equal(store.getInteraction(interaction.id).decision.answers['Hangi ortamda devam edelim?'], 'Pilot');
  const planText = '# Pilot planı\n\n1. Yalnız test sonucunu raporla.';
  const plan = store.createInteraction({ sessionId: session.id, generation: session.generation, requestId: 'browser-fixture-plan', kind: 'plan', toolName: 'ExitPlanMode', input: { plan: planText }, expiresAt: new Date(Date.now() + 600000).toISOString() });
  store.updateSession(session.id, { state: 'permission_required' });
  await answerButton.click();
  await page.getByRole('dialog', { name: 'Plan kararı' }).waitFor();
  assert.equal(await page.locator('.tool-preview').textContent(), planText, 'plan metni aynen gösterilir');
  const approvePlan = page.getByRole('button', { name: 'Bir kez onayla', exact: true });
  assert.equal(await approvePlan.isDisabled(), true, 'plan incelendi onayı gereklidir');
  await page.getByRole('checkbox', { name: /Gösterilen plan sürümünü inceledim/ }).check();
  await approvePlan.click();
  await waitFor(() => store.getInteraction(plan.id).status === 'answered', 'plan onayı');
  assert.equal(store.getInteraction(plan.id).decision.behavior, 'allow');
  assert.equal(store.getInteraction(plan.id).contentHash, plan.contentHash);
  assert.equal(store.getInteraction(plan.id).appliedAt, null, 'UI kararı runner uygulaması sayılmaz');
  const missingPlan = store.createInteraction({ sessionId: session.id, generation: session.generation, requestId: 'browser-fixture-missing-plan', kind: 'plan', toolName: 'ExitPlanMode', input: {}, expiresAt: new Date(Date.now() + 600000).toISOString() });
  await answerButton.click();
  await page.getByText('Bu istekte plan metni bulunmuyor.', { exact: false }).waitFor();
  await page.getByRole('checkbox', { name: /Gösterilen plan sürümünü inceledim/ }).check();
  assert.equal(await approvePlan.isDisabled(), true, 'eksik plan onaylanamaz');
  await page.keyboard.press('Escape');
  store.cancelInteraction(missingPlan.id, session.generation);
  await page.getByRole('button', { name: 'Ayarlar', exact: true }).last().click();
  await page.getByLabel('Proje bildirimleri').focus();
  await page.keyboard.press('Space');
  await waitFor(() => store.listProjects()[0].pushEnabled, 'proje bildirimi');
  await page.getByRole('heading', { name: 'Proje profilleri' }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: path.join(output, 'settings-mobile.png') });
  await context.setOffline(true);
  await waitFor(async () => (await page.getByText('Çevrimdışı', { exact: false }).count()) > 0, 'çevrimdışı');
  assert.equal(await page.getByLabel('Proje bildirimleri').isDisabled(), true);
  await context.setOffline(false);
  const cookies = await context.cookies();
  const identity = auth.authenticate(cookies.find(c => c.name === 'intrem_session').value);
  assert.ok(identity);
  const cursor = store.cursor();
  const abort = new AbortController();
  const stream = await fetch(`${origin}/api/events/stream?after=0`, { headers: { cookie: `intrem_session=${cookies.find(c => c.name === 'intrem_session').value}`, 'Last-Event-ID': String(cursor) }, signal: abort.signal });
  const reader = stream.body.getReader();
  let received = new TextDecoder().decode((await reader.read()).value);
  store.event('test.replay', null, { checked: true });
  received += new TextDecoder().decode((await reader.read()).value);
  assert.ok(received.includes('test.replay'));
  assert.equal(received.includes('project.created'), false);
  auth.revokeDevice(identity.device.id);
  let ended = false;
  await waitFor(async () => { const item = await reader.read(); ended = item.done; return ended; }, 'SSE iptali');
  abort.abort();
  await waitFor(async () => (await page.getByRole('heading', { name: /Çalışmanıza bağlanın|İlk cihazınızı bağlayın/ }).count()) > 0, 'cihaz iptali');
  assert.deepEqual(errors, []);
  console.log(JSON.stringify({ ok: true, checks: ['passkey-register', 'project-session-ui', 'question-answer', 'plan-content-confirmation', 'missing-plan-denied', 'keyboard-dialog-focus-return', 'keyboard-question-and-settings', 'mobile-send-visible', 'project-push-preference', 'responsive-320-1440', 'offline-disable', 'SSE-replay-cursor', 'device-revoke-SSE', 'unknown-delivery-reload-idempotency', 'review-request-ui', 'public-guide-and-auth-return', 'guide-keyboard-and-touch', 'guide-responsive-theme-zoom', 'short-viewport-composer'], screenshots: output }));
} finally {
  await browser?.close();
  await app.close(); store.close();
  rmSync(dir, { recursive: true, force: true });
}
